# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(760, 500, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(890, 500, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.inputlabel = QtWidgets.QLabel(self.centralwidget)
        self.inputlabel.setGeometry(QtCore.QRect(710, 120, 72, 15))
        self.inputlabel.setObjectName("inputlabel")
        self.inputframe = QtWidgets.QLineEdit(self.centralwidget)
        self.inputframe.setGeometry(QtCore.QRect(830, 110, 113, 21))
        self.inputframe.setObjectName("inputframe")
        self.outputframe = QtWidgets.QTextBrowser(self.centralwidget)
        self.outputframe.setGeometry(QtCore.QRect(700, 190, 281, 192))
        self.outputframe.setObjectName("outputframe")
        self.outputlable = QtWidgets.QLabel(self.centralwidget)
        self.outputlable.setGeometry(QtCore.QRect(710, 170, 72, 15))
        self.outputlable.setObjectName("outputlable")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 72, 15))
        self.label.setObjectName("label")
        self.friendipLabel = QtWidgets.QLabel(self.centralwidget)
        self.friendipLabel.setGeometry(QtCore.QRect(120, 30, 201, 16))
        self.friendipLabel.setObjectName("friendipLabel")
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoLabel.setGeometry(QtCore.QRect(0, 50, 671, 421))
        self.videoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videoLabel.setObjectName("videoLabel")
        self.friendnameFrame = QtWidgets.QLineEdit(self.centralwidget)
        self.friendnameFrame.setGeometry(QtCore.QRect(830, 20, 113, 21))
        self.friendnameFrame.setObjectName("friendnameFrame")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(711, 20, 101, 20))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 26))
        self.menubar.setObjectName("menubar")
        self.menuCRYPT_leileqi = QtWidgets.QMenu(self.menubar)
        self.menuCRYPT_leileqi.setObjectName("menuCRYPT_leileqi")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCRYPT_leileqi.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "挂断"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel"))
        self.inputlabel.setText(_translate("MainWindow", "输入"))
        self.outputlable.setText(_translate("MainWindow", "输出"))
        self.label.setText(_translate("MainWindow", "对方IP:"))
        self.friendipLabel.setText(_translate("MainWindow", "0.0.0.0"))
        self.videoLabel.setText(_translate("MainWindow", "视频窗口"))
        self.label_4.setText(_translate("MainWindow", "输入对方名字"))
        self.menuCRYPT_leileqi.setTitle(_translate("MainWindow", "CRYPT-leileqi"))
